apiVersion: v1
kind: Service
metadata:
  name: mckmt-agent
  labels:
    app: mckmt-agent
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: mckmt-agent
