apiVersion: v1
kind: Service
metadata:
  name: mckmt-hub
  labels:
    app: mckmt-hub
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: grpc
  selector:
    app: mckmt-hub
---
apiVersion: v1
kind: Service
metadata:
  name: mckmt-hub-external
  labels:
    app: mckmt-hub
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8080
    protocol: TCP
    name: https
  selector:
    app: mckmt-hub
