services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: mckmt-postgres
    environment:
      POSTGRES_DB: ${MCKMT_DATABASE_NAME:-mckmt}
      POSTGRES_USER: ${MCKMT_DATABASE_USER:-mckmt}
      POSTGRES_PASSWORD: ${MCKMT_DATABASE_PASSWORD:-mckmt}
    ports:
      - "${MCKMT_DATABASE_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MCKMT_DATABASE_USER:-mckmt} -d ${MCKMT_DATABASE_NAME:-mckmt}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Database Migration Init Container
  db-init:
    image: migrate/migrate:latest
    container_name: mckmt-db-init
    environment:
      - PGPASSWORD=${MCKMT_DATABASE_PASSWORD:-mckmt}
    depends_on:
      postgres:
        condition: service_healthy
    command: ["-path", "/migrations", "-database", "postgres://${MCKMT_DATABASE_USER:-mckmt}:${MCKMT_DATABASE_PASSWORD:-mckmt}@postgres:${MCKMT_DATABASE_PORT:-5432}/${MCKMT_DATABASE_NAME:-mckmt}?sslmode=disable", "up"]
    volumes:
      - ./migrations:/migrations:ro

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: mckmt-redis
    ports:
      - "${MCKMT_REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MCKMT Hub API
  hub:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile.hub
    container_name: mckmt-hub
    ports:
      - "${MCKMT_SERVER_PORT:-8080}:8080"
      - "${MCKMT_GRPC_PORT:-8081}:8081"
    environment:
      - MCKMT_DATABASE_HOST=postgres
      - MCKMT_DATABASE_PORT=${MCKMT_DATABASE_PORT:-5432}
      - MCKMT_DATABASE_USER=${MCKMT_DATABASE_USER:-mckmt}
      - MCKMT_DATABASE_PASSWORD=${MCKMT_DATABASE_PASSWORD:-mckmt}
      - MCKMT_DATABASE_NAME=${MCKMT_DATABASE_NAME:-mckmt}
      - MCKMT_REDIS_HOST=redis
      - MCKMT_REDIS_PORT=${MCKMT_REDIS_PORT:-6379}
      - MCKMT_JWT_SECRET=${MCKMT_JWT_SECRET:-your-super-secret-jwt-key}
      - MCKMT_SERVER_HOST=0.0.0.0
      - MCKMT_SERVER_PORT=8080
    depends_on:
      db-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    volumes:
      - ../../configs:/app/configs:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MCKMT Agent (example agent for testing)
  agent:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile.agent
    container_name: mckmt-agent
    environment:
      - MCKMT_HUB_URL=http://hub:8080
      - MCKMT_AGENT_ID=test-agent-1
      - MCKMT_CLUSTER_ID=test-cluster-1
      - MCKMT_KUBECONFIG_PATH=/app/kubeconfig
    depends_on:
      hub:
        condition: service_healthy
    volumes:
      - ../../configs:/app/configs:ro
      # In real deployment, this would be a real kubeconfig
      - ./kubeconfig:/app/kubeconfig:ro
    restart: unless-stopped

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: mckmt-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../../configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - hub

  # Grafana for dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: mckmt-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ../../configs/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ../../configs/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    depends_on:
      - prometheus

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:
