# MCKMT Hub Configuration with OIDC enabled
# This is a sample configuration file for OIDC authentication

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

grpc:
  host: "0.0.0.0"
  port: 9090
  max_connection_age: "2h"
  max_connection_age_grace: "30s"
  time: "2h"
  timeout: "20s"

database:
  host: "localhost"
  port: 5432
  user: "mckmt"
  password: "mckmt123"
  dbname: "mckmt"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: "5m"

redis:
  host: "localhost:6379"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5

auth:
  jwt:
    secret: "your-super-secret-jwt-key-change-this-in-production"
    expiration: "24h"
  
  # OIDC Configuration
  oidc:
    enabled: true
    issuer: "http://localhost:8081/realms/mckmt"
    client_id: "mckmt-hub"
    client_secret: "mckmt-client-secret-123"
    redirect_url: "http://localhost:8080/auth/oidc/callback"
    scopes: ["openid", "profile", "email"]

  # Password configuration
  password:
    min_length: 8
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special_chars: true

  # RBAC configuration
  rbac:
    enabled: true
    default_role: "viewer"

orchestrator:
  workers: 3
  operation_timeout: "30m"
  retry_attempts: 3
  retry_delay: "5s"

logging:
  level: "info"
  format: "json"
  output: "stdout"

metrics:
  enabled: true
  path: "/metrics"
  port: 9091
