apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mckmt-system

resources:
  - ../../base

patches:
  - path: agent-production-patch.yaml
    target:
      kind: Deployment
      name: mckmt-agent

configMapGenerator:
  - name: mckmt-agent-config
    literals:
      - MCKMT_HUB_HOST=mckmt-hub.mckmt-system.svc.cluster.local
      - MCKMT_HUB_PORT=8080
      - MCKMT_GRPC_PORT=8081
      - MCKMT_LOGGING_LEVEL=info
      - MCKMT_CLUSTER_NAME=mckmt-production-cluster
      - MCKMT_AGENT_HEARTBEAT_INTERVAL=60s

labels:
  - pairs:
      environment: production
      app.kubernetes.io/instance: production

images:
  - name: mckmt-agent
    newTag: v1.0.0
