# MCKMT Configuration File
# This file contains default configuration values
# Environment variables with MCKMT_ prefix will override these values

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"
  tls:
    enabled: false
    cert_file: ""
    key_file: ""

grpc:
  host: "0.0.0.0"
  port: 8081
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"
  tls:
    enabled: false
    cert_file: ""
    key_file: ""

database:
  host: "localhost"
  port: 5432
  user: "mckmt"
  password: "mckmt"
  database: "mckmt"
  ssl_mode: "disable"
  max_conns: 25
  min_conns: 5
  max_conn_life: "1h"
  max_conn_idle: "30m"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  max_retries: 3
  min_retry_backoff: "8ms"
  max_retry_backoff: "512ms"
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"
  pool_size: 10
  min_idle_conns: 5
  max_conn_age: "30m"
  pool_timeout: "4s"
  idle_timeout: "5m"
  idle_check_freq: "1m"

auth:
  oidc:
    enabled: false
    issuer: ""
    client_id: ""
    client_secret: ""
    redirect_url: ""
    scopes: ["openid", "profile", "email"]
  jwt:
    secret: "your-super-secret-jwt-key-change-in-production"
    expiration: "24h"
    issuer: "mckmt"
    audience: "mckmt-users"
  rbac:
    enabled: true
    default_role: "viewer"

agent:
  hub_url: "localhost:8081"
  agent_id: ""
  cluster_id: ""
  heartbeat_interval: "30s"
  operation_timeout: "5m"
  max_retries: 3
  retry_backoff: "1s"

orchestrator:
  workers: 5

logging:
  level: "info"
  format: "json"
  caller: false
  stacktrace: false
  output_paths: ["stdout"]
  error_output_paths: ["stderr"]

metrics:
  enabled: true
  path: "/metrics"
  port: 9090